apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
      - name: gpt-descriptions-generator
        image: mutiaracitra/gpt-descriptions-generator:latest # Ganti dengan nama image yang valid
        ports:
        - containerPort: 5001
